const nodemailer = require("nodemailer");
const config = require("../config/config");

let transporter;

/**
 * Initialize and return the nodemailer transporter.
 * If credentials are missing in the config, it falls back to Ethereal Email for testing.
 */
const getTransporter = async () => {
    if (transporter) return transporter;

    const isEthereal = config.email.host.includes("ethereal");
    const hasCredentials =
        config.email.user &&
        config.email.pass &&
        !config.email.user.includes("your_") &&
        !config.email.pass.includes("your_");

    let mailConfig;

    if (isEthereal && !hasCredentials) {
        console.log(
            "No valid Ethereal credentials found. Creating ephemeral account...",
        );
        const testAccount = await nodemailer.createTestAccount();
        mailConfig = {
            host: "smtp.ethereal.email",
            port: 587,
            secure: false,
            auth: {
                user: testAccount.user,
                pass: testAccount.pass,
            },
        };
        console.log(`Ethereal Test User: ${testAccount.user}`);
        console.log(`Ethereal Test Pass: ${testAccount.pass}`);
    } else {
        mailConfig = {
            host: config.email.host,
            port: parseInt(config.email.port, 10) || 587,
            secure: config.email.port == 465,
            auth: {
                user: config.email.user,
                pass: config.email.pass,
            },
        };
    }

    transporter = nodemailer.createTransport(mailConfig);
    return transporter;
};

const sendEmail = async ({ to, subject, text, html }) => {
    try {
        const mailTransporter = await getTransporter();

        // Use the actual user from the transporter (especially if it was auto-generated by Ethereal)
        const senderUser = mailTransporter.options.auth.user;

        const info = await mailTransporter.sendMail({
            from: `"Dashboard Support" <${senderUser}>`,
            to,
            subject,
            text,
            html,
        });

        console.log("Message sent: %s", info.messageId);

        // Preview URL only works if using an Ethereal account
        const previewUrl = nodemailer.getTestMessageUrl(info);
        if (previewUrl) {
            console.log("Preview URL: %s", previewUrl);
        }

        return info;
    } catch (error) {
        console.error("Error sending email:", error);
        throw error;
    }
};

const sendPasswordResetEmail = async (email, token) => {
    // Determine user front-end URL from config if possible, or use local default
    const resetUrl = `${config.FRONTEND_URL}/reset-password?token=${token}`;
    const subject = "Password Reset Request";
    const text = `You are receiving this email because you (or someone else) have requested the reset of the password for your account.\n\nPlease click on the following link, or paste this into your browser to complete the process within one hour of receiving it:\n\n${resetUrl}\n\nIf you did not request this, please ignore this email and your password will remain unchanged.\n`;
    const html = `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <h2 style="color: #4A90E2;">Password Reset Request</h2>
            <p>You are receiving this email because you (or someone else) have requested the reset of the password for your account.</p>
            <p>Please click on the button below to reset your password. This link is valid for 1 hour.</p>
            <div style="margin: 20px 0;">
                <a href="${resetUrl}" style="background-color: #4A90E2; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; font-weight: bold;">Reset Password</a>
            </div>
            <p>Or copy and paste this link into your browser:</p>
            <p><a href="${resetUrl}">${resetUrl}</a></p>
            <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
            <p style="font-size: 0.8em; color: #777;">If you did not request this, please ignore this email and your password will remain unchanged.</p>
        </div>
    `;

    return sendEmail({ to: email, subject, text, html });
};

module.exports = {
    sendEmail,
    sendPasswordResetEmail,
};
